services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shipments_1
    networks:
      - airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    

  redis:
    image: redis:latest
    networks:
      - airflow

  mongo:
    image: mongo:latest
    networks:
      - airflow
    volumes:
      - mongo_data:/data/db

  airflow-init:
    image: apache/airflow:2.5.0
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres/shipments_1
    entrypoint: ["airflow", "db", "init"]
    networks:
      - airflow
    depends_on:
      - postgres

  airflow-webserver:
    image: apache/airflow:2.5.0
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres/shipments_1
      AIRFLOW_CONN_MONGO_DEFAULT: mongodb://mongo:27017
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://postgres:postgres@postgres/shipments_1
    ports:
      - "8080:8080"
    networks:
      - airflow
    depends_on:
      - postgres
      - redis

  airflow-worker:
    image: apache/airflow:2.5.0
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres/shipments_1
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://postgres:postgres@postgres/shipments_1
    networks:
      - airflow
    depends_on:
      - postgres
      - redis

networks:
  airflow:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
